version: '2'

services:
  db:
    image: postgres:9.4
    ports:
      - "5432"
  api:
    build:
      context: ./watchibot-api
      dockerfile: dockerfile.api.${NODE_ENV}
    command: >
      sh -c '
        export NODE_ENV=${NODE_ENV}
        node_modules/.bin/nodemon index.js
      '
    volumes:
      - ./watchibot-api:/home/app/api_volume
      - /home/app/api_volume/node_modules
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
  app:
    build:
      context: ./watchibot-app
      dockerfile: dockerfile.app.${NODE_ENV}
    command: >
      sh -c '
        export NODE_ENV=${NODE_ENV}
        npm start
      '
    volumes:
      - ./watchibot-app:/home/app/app_volume
      - /home/app/app_volume/node_modules
    links:
      - api
    depends_on:
      - api
    ports:
      - "8081:8080"
